# Generated by Django 5.2 on 2025-04-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_users', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
    ]
